config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  devise_for :users

  resources :users
  resources :companies
  resources :u_to_c_likes, only: [:create]
  resources :u_to_c_likes, only: [:create]

  root 'companies#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #association
  has_many :u_to_c_likes
  has_many :company, through: :u_to_c_likes

  def name_method
    "#{last_name} #{first_name}"
  end

  def name_kana_method
    "#{last_name_kana} #{first_name_kana}"
  end

  def birthday_method
    "#{birth_y}年 #{birth_m}月 #{birth_d}日"
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @likes = @user.u_to_c_likes
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sign_for_companies.html.erb
<% if company_signed_in? %>
  <%= link_to "採用担当者様用ログアウト", destroy_company_session_path, method: :delete %>
<% else %>
  <%= link_to "採用担当者様用　会員登録",new_company_registration_path, class: 'post' %>
  <%= link_to "採用担当者様用　ログイン", new_company_session_path, class: 'post' %>
<% end %>

app/views/users/index.html.erb
<div class="row clearfix">
  <ul class="grid">
    <% @users.each do |user| %>
      <li class="box">
        <a href="/users/<%= user.id %>" class="inner_grid clearfix">
          <img src="" alt="">
          <h3 class="small_subject"><%= user.name_method %></h3>
          <h3 class="big_subject"><%= user.birthday_method %></h3>
          <span class="small_subject"><%= user.job_history %></span>
          <figure class="square">詳細</figure>
        </a>
      </li>
    <% end %>
  </ul>
</div>

<%= render partial: "users/sign_for_companies" %>

app/views/users/show.html.erb
<div class="row">

  <div class="right clearfix">
    <h1>
      <span class="small_subject"><%= @user.name_kana_method %></span><br>
      <span class="small_subject">名前</span> <span><%= @user.name_method %></span>
    </h1>
  </div>

  <hr class="dotted">
  <div class="inner_row left clearfix">
    <h2 class="big_subject" style="color:#d75452;">LIKEした企業</h2>
  </div>
  <hr class="dotted">

    <% @likes.each do |like| %>
      <ul class="grid">
        <li class="box">
          <a href="/companies/<%= like.company.id %>" class="inner_grid clearfix">
            <img src="<%= like.company.image_url %>" alt="<%= like.company.name %>画像">
            <h3 class="small_subject">
              <%= like.company.name %>
            </h3>
            <h3 class="big_subject">
              <%= like.company.catch_copy %>
            </h3>
            <span class="small_subject">
              <%= like.company.location %>
            </span>
            <p> 教育コストの自己負担学<br /><span class="big_subject"><%= like.price %>万円</span>で応募済 </p>
            <figure class="square">詳細</figure>
          </a>
        </li>
      </ul>
    <% end %>

  <hr class="dotted">
    プロフィール<br>
  <hr class="dotted">

  <div class="inner_row left clearfix">
    <h3 class="blue_rocket">生年月日</h3>
      <p class="blue_">
        <%= @user.birthday_method %>
      </p>
  </div>

  <hr class="dotted">

  <div class="inner_row left clearfix">
    <h3 class="blue_rocket">住所</h3>
      <p>
        <%= @user.address %>
      </p>
  </div>

  <hr class="dotted">

    <div class="inner_row left clearfix">
    <h3 class="blue_rocket">住所</h3>
      <p>
        <%= @user.address %>
      </p>
  </div>

  <hr class="dotted">

  <div class="inner_row left clearfix">
    <h3 class="blue_rocket">最終学歴</h3>
      <p>
        <%= @user.final_education %>
      </p>
  </div>

  <hr class="dotted">

  <div class="inner_row left clearfix">
    <h3 class="blue_rocket">職務経歴</h3>
      <p>
        <%= @user.job_history %>
      </p>
  </div>

  <hr class="dotted">


</div>