config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  devise_for :users

  resources :users
  resources :companies
  resources :u_to_c_likes, only: [:create]
  resources :u_to_c_likes, only: [:create]

  root 'companies#index'

end

app/models/c_to_u_like.rb
class CToULike < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #association
  has_many :u_to_c_likes
  has_many :users, through: :u_to_c_likes
end

app/models/u_to_c_like.rb
class UToCLike < ActiveRecord::Base
  #association
  belongs_to :user
  belongs_to :company

  #validation
  validates :price, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #association
  has_many :u_to_c_likes
  has_many :company, through: :u_to_c_likes

  def name_method
    "#{last_name} #{first_name}"
  end

  def name_kana_method
    "#{last_name_kana} #{first_name_kana}"
  end

  def birthday_method
    "#{birth_y}年 #{birth_m}月 #{birth_d}日"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters,if: :devise_controller?

  #deviseのサインアップで許可するパラメーターを指定
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name,:last_name,:first_name,:last_name_kana,:first_name_kana]

  end
end

app/controllers/c_to_u_likes_controller.rb
class CToULikesController < ApplicationController

  

end

app/controllers/companies/passwords_controller.rb
class Companies::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/companies/sessions_controller.rb
class Companies::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/companies/unlocks_controller.rb
class Companies::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def edit
  end

  def update
    current_company.update(update_params)
  end

  def show
    @company = Company.find(params[:id])
    @u_to_c_like = UToCLike.new
  end

  private
  def update_params
    params.require(:company).permit(:name)
  end
end

app/controllers/u_to_c_likes_controller.rb
class UToCLikesController < ApplicationController

  def create
    UToCLike.create(create_params)
    redirect_to :root and return
  end

  private
  def create_params
    params.require(:u_to_c_like).permit(:price, :company_id).merge(user_id: current_user.id)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @likes = @user.u_to_c_likes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/c_to_u_likes_helper.rb
module CToULikesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/u_to_c_likes_helper.rb
module UToCLikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobmart3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>
</head>
<body>
<header class="header">
  <div class="container clearfix">
    <%= link_to "JOB MART",root_path, class: [:site_title, :header_menu_left] %>
    <% if user_signed_in? %>
      <%= link_to "ログアウト", destroy_user_session_path, class: 'header_menu_right', method: :delete %>
      <%= link_to "マイページ",user_path(current_user), class: :header_menu_right %>
    <% else %>
      <%= link_to "新規登録",new_user_registration_path, class: 'header_menu_right' %>
      <%= link_to "サインイン",new_user_session_path, class: 'header_menu_right' %>

    <% end %>

  </div>
</header>
<%= yield %>

<fotter>
  <div class="row">
    <a href="/users">採用ご担当者様へ</a>
  </div>
</fotter>
</body>
</html>

app/views/layouts/for_companies.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobmart3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>
</head>
<body>
<header class="header">
  <div class="container clearfix">
    <%= link_to "JOB MART",root_path, class: [:site_title, :header_menu_left] %>
    <% if user_signed_in? %>
      <%= link_to "ログアウト", destroy_company_session_path, method: :delete %>
      <%= link_to "マイページ",user_path(current_user), class: :header_menu_right %>
    <% else %>
      <%= link_to "新規登録",new_company_registration_path, class: 'post' %>
      <%= link_to "ログイン", new_company_session_path, class: 'post' %>

    <% end %>

  </div>
</header>
<%= yield %>

<fotter>
  <div class="row">
    <a href="/companies">求職者の方はこちら</a>
  </div>
</fotter>
</body>
</html>